<div id="moveWrapper" class="hidden" >
<p class="close_popup2"
	onclick='$("#moveWrapper").togglePopup(); ' title="отмена"></p>
<h5>Переместить пользователя</h5>
<form
<?php

foreach ($this->formMove->getAttribs() as $key => $atribute)
{
	echo $key.'='.'"'.$atribute.'" ';
}
?>>
<p>Группа  получатель</p>
<?php 	echo $this->formMove->id->removeDecorator('Description'); ?> 
 
<?php 	echo $this->formMove->destination->removeDecorator('Description'); ?> 

<p> <?php 	echo $this->formMove->OK->removeDecorator('Description'); ?> </p>
</form>
</div>