<?php echo $this->render('header.phtml'); ?>

<?php if(!empty($this->message)) :?>
<div id="message">
<?php echo $this->escape($this->message);?>
</div>
<?php endif; ?>

<form action="<?php echo $this->baseUrl ?>/auth/login" method="post">
<div>
    <label for="username">Пользователь</label>
    <input type="text" name="username" value=""/>
</div>
<div>
    <label for="password">Пароль</label>
    <input type="password" name="password" value=""/>
</div>
<div id="formbutton">
<input type="submit" name="login" value="Login" />
</div>
</form>

<?php echo $this->render('footer.phtml'); ?>