<?php 
    /** 
     * @TODO все менюшки при записи в БД должны быть:
     * кнопки в форме должны быть: ПРИМЕНИТЬ, СОХРАНИТЬ, ВЕРНУТЬ, ЗАКРЫТЬ
     * при нажатии ПРИМНЕИТЬ - вносит в БД не заакрывая
     * при нажатии СОХРАНИТЬ - вносит в БД и возвращает на пред. страницу
     * при нажатии ВЕРНУТЬ - возвращает из БД
     * при нажатии ЗАКРЫТЬ - вернутся на предыдущую стр.
     */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru-ru" lang="ru-ru">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->escape($this->title); ?></title>
<link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<?php echo $this->baseUrl;?>/public/images/favicon.ico" />
<link rel="stylesheet" type="text/css" media="screen"
	href="<?php echo $this->baseUrl;?>/public/styles/site.css" />
<link rel="stylesheet" type="text/css" media="screen"
	href="<?php echo $this->baseUrl;?>/public/styles/icos.css" />
<!--Jquery UI-->
<link rel="stylesheet" type="text/css" 
	href="<?php echo $this->baseUrl;?>/public/styles/south-street/jquery-ui-1.9.2.custom.min.css" />
<link rel="stylesheet" type="text/css" media="print"
	href="<?php echo $this->baseUrl;?>/public/styles/print.css" />
<!--стили-->
<?php echo $this->headLink(); ?>
	
<script type="text/javascript"> 
	my_baseUrl="<?php echo $this->baseUrl; ?>"; 
</script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery-ui-1.9.2.custom.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.form.js" type="text/javascript"></script>
<!-- 
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.core.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.datepicker.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.widget.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.mouse.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.slider.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.tabs.min.js" type="text/javascript"></script>
 -->
<script src="<?php echo $this->baseUrl;?>/public/scripts/jquery.ui.datepicker-ru.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/my.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/tabs.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/popups.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/public/scripts/togglExpColla.js" type="text/javascript"></script>

<?php echo $this->headScript(); ?>

<?php echo $this->headStyle(); ?>

	
</head>
<body>
<div id="opaco" class="hidden"></div>
<div id="popup" class="hidden"></div>

<div id="ajaxLoader" style="display:none;" >Обработка запроса <img src="<?php echo $this->baseUrl; ?>/public/images/ajax-loader_book.gif" /></div>


    <?php 
            $this->user = Zend_Auth::getInstance()->getIdentity();
    
    if($this->user) : ?>

<?php
$front = Zend_Controller_Front::getInstance();
$request = $front->getRequest();
$module = $request->getModuleName();
$controller = $request->getControllerName();

?>

<div id="left">
<!--<pre><?php // echo print_r($this->navigation()->menu(),true);?></pre>-->
    <?php
	// @FIXME - хак, ессли попадаем на HELPDESK то остальные менюшки не показывать
	if ($module=="helpdesk")
	{
		$_nav=$this->navigation()-> findBy("module","helpdesk");
		// почемуто потерялся родительский пункт меню 
		$_p=array(
				"label"=>$_nav->getLabel(),
				"class"=>$_nav->getClass(),
				"type"=>"mvc",
				"module"=>"helpdesk",
				"controller"=>"index"
				);
		$_nav->addPage($_p);
		$options = array(
				'renderParents' => true,
				"setExpandSiblingNodesOfActiveBranch"=>true
		);
		echo $this->navigation()->menu()->renderMenu($_nav,$options);
// 		echo "<pre>".print_r(get_class_methods($_nav),true)."</pre>";
	}
	else echo $this->navigation()->menu(); 
    ?>
</div>

<?php endif; ?> 
<div id="content">
 
 <?php
 // титул страницы
 
 $moduleTitle=Zend_Registry::get("ModuleTitle");
 $modContrTitle=Zend_Registry::get("ModuleControllerTitle");
 
 // @TODO это костыль
//  if ($module."-".$controller==="default-index") $title="Краткая справка";
//  else $title=$moduleTitle.". ".$modContrTitle.'. ';  
	$title=$moduleTitle.". ".$modContrTitle.'. ';  
//  $action = $request->getActionName();
 
 
 ?>
 <h1><?php echo $title; ?></h1>
  
 <?php
 // мы находимся MODULE-INDEX и залогинены ли?
 if ( $this->user && $controller=="index") 
 {
	//  	есть ли аннотация к данному модулю? 
 	$annot = Zend_Registry::isRegistered("moduleAnnot") ? Zend_Registry::get("moduleAnnot") :"";
 	?>
 	<div id="annotation">
 	<?php echo $annot; ?>
 	</div>
 	<?php 
 }
 
 
 ?>
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
