<div id="ticketsList">
<?php 
if (empty($this->list))
{
	echo "Не обнаружено";

}
else
{
?>
	<table id="tList">
		<thead>
		<tr >
			<th >Дата подачи</th>
			<th >Дата закрытия</th>
			<th >Подразделение</th>
		</tr>
		</thead>
		<tbody>
	<?php
	// какойто костыль
	$_acl=Zend_Registry::get("ACL");
	foreach ($this->list as $item) 
	{
		$gr_title=empty($item["tfio"])?$item["gr_title"]:$item["tfio"].", ".$item["tdep"];
		$gr_title.=". ".$item["place"];
		// есть ли доступ к перечню в подразделении
		// @TODO както криво все по другому надо
		if($_acl->isAllowed($this->author,"helpdesk-departments","list"))
		{
			$lnk=$this->baseUrl."/".$this->currentModuleName."/departments/list/id/".$item["gr_id"];
			$lnk='<a href="'.$lnk.'" >'.$gr_title."</a>";
		}
		else 
		{
			$lnk=$gr_title;
		}
		
		$tr=$tr===1?2:1;
		if ($item["closed"]==="0000-00-00 00:00:00")
		{
			$_closed="в работе";
			$_closStyle="";
		}
		else
		{
			$_closed="закрыто ".substr($item["closed"],0,10);
			$_closStyle='id="disabledTicket"';
		}
// 		$_closed=$item["closed"]==="0000-00-00 00:00:00"
// 				? "в работе"
// 				: "закрыто ".substr($item["closed"],0,10);
		// открытые и старше 14 суток
		$_oldStyle=$item["daysOld"]>=14 && $item["closed"]==="0000-00-00 00:00:00" ? "warningIcoSmall" :"";
		$_oldTitle=$item["daysOld"]>=14 && $item["closed"]==="0000-00-00 00:00:00" ? "В работе более 14 суток" :"";
		?>
		
		<tr <?php echo $_closStyle; ?> class="tr<?php echo $tr;?>">
			<td class="inlineLink" onclick="ticketView(<?php echo $item["id"];?>);">
				<?php echo substr($item["created"],0,10);?>&nbsp;<small><sup><?php echo substr($item["created"],11);?></sup></small>
			</td>
			<td >
				<?php echo $_closed;?>
				<span class="<?php echo $_oldStyle; ?>" title="<?php echo $_oldTitle; ?>"></span>
			</td>
			<td >
				<?php echo $lnk; ?>
			</td>
		<?php 
			
		?>
		</tr>
		
		<?php		
	}
	?>
	</tbody>
	</table>

	<?php
} 
?>	
</div>
<script type="text/javascript" language="javaScript">
$(document).ready(function() {
    $('#tList').dataTable({
    		 "bPaginate": false,
    		 "bSortClasses": false,
    		 "bInfo ":false,
    		 "bFilter":true,
		      "aaSorting": 	[[0,'desc']],
    		 "oLanguage": {
    		      "sInfo": "Найдено элементов: _TOTAL_  (с _START_ по _END_)",
    		      "sInfoFiltered": " - отфильтровано из _MAX_ записей",
    		      "sInfoEmpty": "Нет элементов для отображения",
    		      "sZeroRecords": "Нет записей для отображения",
    		      "sSearch": "Найти:"
    		    }
    		 /*"bJQueryUI":true*/
    } );
} );
</script>