<?php echo $this->render('header.phtml'); ?>


<div id="left">
<ul>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/resources">Объекты доступа</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/roles">Группы (роли)</a></li>
<!--<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/privelegies">Привилегии</a></li>-->
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/users">Пользователи</a></li>
<li><a href="<?php echo $this->baseUrl; ?>/<?php echo $this->currentModuleName; ?>/menus">Меню</a></li>
</ul>
</div>