<form
<?php 

foreach ($this->form->getAttribs() as $key => $atribute)
{
    echo $key.'='.'"'.$atribute.'"';
}
?>>
<?php echo $this->form->id;?>
<h5>Параметры внешнего вида генерируемой ссылки</h5>
<div class="tr1">
	<div class="Col_1">Название пункта</div>
	<div class="Col_2"><?php echo $this->form->label;?></div>
</div>
<div class="tr2">
	<div class="Col_1">Описание, параметр TITLE</div>
	<div class="Col_2"><?php echo $this->form->title;?></div>
</div>
<div class="tr1">
	<div class="Col_1">CSS класс</div>
	<div class="Col_2"><?php echo $this->form->class;?></div>
</div>
<div class="tr2">
	<div class="Col_1">_TARGET</div>
	<div class="Col_2"><?php echo $this->form->target;?></div>
</div>
<h5>Управление доступом</h5>
<div class="tr2">
	<div class="Col_1">ACL: ресурс</div>
	<div class="Col_2"><?php echo $this->form->resource;?></div>
</div>
<div class="tr1">
	<div class="Col_1">ACL: привилегии</div>
	<div class="Col_2"><?php echo $this->form->privilege;?></div>
</div>
<div class="tr2">
	<div class="Col_1">ACL: доступ разрешен для</div>
	<div class="Col_2"><?php echo $this->form->rolesList;?></div>
</div>
<h5>Маршрут</h5>
<div class="tr1">
	<div class="Col_1">MVC: модуль</div>
	<div class="Col_2"><?php echo $this->form->module;?></div>
</div>
<div class="tr2">
	<div class="Col_1">MVC: контроллер</div>
	<div class="Col_2">
		<div id="controllerList">
			<?php echo $this->form->controller;?>
		</div>
	</div>
</div>
<div class="tr1">
	<div class="Col_1">MVC: action</div>
	<div class="Col_2">
		<div id="actionList">
			<?php echo $this->form->action;?>
		</div>
	</div>
</div>
<div class="tr2">
	<div class="Col_1">MVC: параметры</div>
	<div class="Col_2"><?php echo $this->form->params;?></div>
</div>
<h5>Прочее</h5>
<div class="tr2">
	<div class="Col_1">Родитель</div>
	<div class="Col_2"><?php echo $this->form->parent;?></div>
</div>
<div class="tr1">
	<div class="Col_1">Порядок сортировки</div>
	<div class="Col_2"><?php echo $this->form->order;?></div>
</div>
<div class="tr2">
	<div class="Col_1">Отключен</div>
	<div class="Col_2"><?php echo $this->form->disabled;?></div>
</div>
<div class="tr1">
	<div class="Col_1"><a href="<?php echo $this->parentLink;?>">Назад</a></div>
	<div class="Col_2"><?php echo $this->form->formSubmit;?>&nbsp;<a href="<?php echo $this->selfLink;?>">Вернуть</a></div>
</div>
</form>